/** Maps a font name used in movie XML to the FontFile*.swf basename shipped in static/.../go/font. */
const FONT_FILES: Record<string, string> = {
  "Blambot Casual": "FontFileCasual",
  "BadaBoom BB": "FontFileBoom",
  "Entrails BB": "FontFileEntrails",
  "Tokyo Robot Intl BB": "FontFileTokyo",
  "Accidental Presidency": "FontFileAccidental",
  BodoniXT: "FontFileBodoniXT",
  "Budmo Jiggler": "FontFileBJiggler",
  "Budmo Jigglish": "FontFileBJigglish",
  "Existence Light": "FontFileExistence",
  HeartlandRegular: "FontFileHeartland",
  "Honey Script": "FontFileHoney",
  "I hate Comic Sans": "FontFileIHate",
  "Impact Label": "FontFileImpactLabel",
  "loco tv": "FontFileLocotv",
  "Mail Ray Stuff": "FontFileMailRay",
  "Mia's Scribblings ~": "FontFileMia",
  Shanghai: "FontFileShanghai",
  "Comic Book": "FontFileComicBook",
  "Wood Stamp": "FontFileWoodStamp",
  Brawler: "FontFileBrawler",
  "Coming Soon": "FontFileCSoon",
  Glegoo: "FontFileGlegoo",
  "Lilita One": "FontFileLOne",
  "Telex Regular": "FontFileTelex",
  "Claire Hand": "FontFileClaireHand",
  Oswald: "FontFileOswald",
  "Poiret One": "FontFilePoiretOne",
  Raleway: "FontFileRaleway",
  Bangers: "FontFileBangers",
  Creepster: "FontFileCreepster",
  BlackoutMidnight: "FontFileBlackoutMidnight",
  BlackoutSunrise: "FontFileBlackoutSunrise",
  Junction: "FontFileJunction",
  LeagueGothic: "FontFileLeagueGothic",
  LeagueSpartan: "FontFileLeagueSpartan",
  OstrichSansMedium: "FontFileOstrichSansMedium",
  Prociono: "FontFileProciono",
  Lato: "FontFileLato",
  "Alegreya Sans SC": "FontFileAlegreyaSansSC",
  Barrio: "FontFileBarrio",
  "Bungee Inline": "FontFileBungeeInline",
  "Bungee Shade": "FontFileBungeeShade",
  "Gochi Hand": "FontFileGochiHand",
  "IM Fell English SC": "FontFileIMFellEnglishSC",
  Josefin: "FontFileJosefin",
  Kaushan: "FontFileKaushan",
  Lobster: "FontFileLobster",
  Montserrat: "FontFileMontserrat",
  "Mouse Memoirs": "FontFileMouseMemoirs",
  "Patrick Hand": "FontFilePatrickHand",
  "Permanent Marker": "FontFilePermanentMarker",
  Satisfy: "FontFileSatisfy",
  Sriracha: "FontFileSriracha",
  Teko: "FontFileTeko",
  Vidaloka: "FontFileVidaloka",
};

export function fontFileName(font: string | undefined | null): string {
  if (!font) return "";
  return FONT_FILES[font] ?? `FontFile${font}`;
}
